apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: 5d5jl
rendezvousIP: 192.168.166.201
hosts:
  - hostname: master-0
    interfaces:
      - name: ens192
        macAddress: 00:50:56:a2:fc:b2
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: ens192
          type: ethernet
          state: up
          mac-address: 00:50:56:a2:fc:b2
          ipv4:
            enabled: true
            address:
              - ip: 192.168.166.201
                prefix-length: 24
            dhcp: false    
      dns-resolver:
        config:
          server:
            - 10.2.192.12    
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.166.1
            next-hop-interface: ens192
            table-id: 254
